config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'alphablog#home'
  get 'about', to: 'alphablog#about'

  resources :articles, only: [:show, :index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article <ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100 }
end

app/controllers/alphablog_controller.rb
class AlphablogController < ApplicationController

  def home; end

  def about; end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    render plain: params[:article]
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end


  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alphablog/about.html.erb
<h1>This is the Alpha Blog About page</h1>

<%= link_to "Home", root_path %>

app/views/alphablog/home.html.erb
<h1>This is the Alpha Blog home page</h1>

<%= link_to "About", about_path %>

app/views/articles/index.html.erb
<h1>Articles Listing Page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article|   %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td>Placeholder</td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= form_with scope: :article,  url: articles_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/show.html.erb
<h1>Showing Selected Article</h1>

<p>Title: <%= @article.title %></p>

<p>Description: <%=@article.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
    <%= yield %>
  </body>
</html>